compiler:
  solc:
    evm_version: paris
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.6"
      - "@layerzerolabs/lz-evm-oapp-v2=node_modules/@layerzerolabs/lz-evm-oapp-v2"
      - "@layerzerolabs/lz-evm-protocol-v2=node_modules/@layerzerolabs/lz-evm-protocol-v2"
  vyper:
    evm_version: paris

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.6

networks:
  default: hardhat

project_structure:
  tests: tests/brownie

autofetch_sources: true
