compiler:
  solc:
    evm_version: paris
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.2"
      - "@layerzero-v2-oapp=vendor/layerzero-v2/oapp"
      - "@layerzerolabs/lz-evm-protocol-v2=vendor/layerzero-v2/protocol"
  vyper:
    evm_version: paris

dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.2

networks:
  default: hardhat

project_structure:
  tests: tests/brownie

autofetch_sources: true
