stablecoin:
  name: "Defi.Money Stablecoin"
  symbol: "MONEY"

main_controller:
  global_debt_ceiling: 100_000_000

peg_keepers:
  worst_price_threshold: 0.001
  price_deviation: 100
  action_delay: 30
  debt_ceiling: 1_000_000
  caller_profit_fraction: 0.2
  pool_config:
    A: 100
    fee: 0.0004
    offpeg_fee_mul: 2
    ma_seconds: 600
  paired_assets: null

stable_oracle:
  sigma: 0.001

monetary_policy:
  sigma: 0.007
  target_debt_fraction: 0.1

core_owner:
  fee_receiver: "0x222d2B30EcD382a058618d9F1ee01F147666E48b"
  start_offset: 302400

curve:
  address_provider: "0x5ffe7FB82894076ECB99A30D6A32e969e6e35E98"

layerzero:
  endpoint: "0x1a44076050125825900e736c501f859c50fE728c"
  primary_eid: 30111
  primary_network: "optimism-main"
  oft_default_options: "0x0003010011010000000000000000000000000000ea60"

chainlink:
  sequencer_uptime: null

odos:
  router: null

whitelist: false

fees:
  weth: null
  fee_converter:
    swap_bonus_pct: 0.5
    relay_min_balance: 0.1
    relay_max_swap_debt_amount: 250
    bridge_bonus_pct: 0.1
    bridge_max_bonus_amount: 50
  fee_agg:
    caller_incentive: 100
  stable_staker:
    cooldown_days: 7
    min_price: 0.99
    max_price: 1.01
    min_pct: 25
    max_pct: 75